### PR TITLE
Update symfony version to 5.0+

### PR DESCRIPTION
**Pull request by vsychov**
Hi,

thank you for this bundle, for now it's little bit outdated and support only symfony 4.*, this PR add support of 5.0+.

Best regards.

### CODE REVIEW

**Comment by nicklog** [comment]
Hey,

thank you. You can try the 3.0 Dev Version.
Please let me know if it works.

Please note, service id and database table have changed.

**Comment by vsychov** [comment]
@nicklog, thanks for merging.

All good, except missed `@ORM\CustomIdGenerator` in Session class for `sessionId` field, can it be fixed? Looks like, that it should be something like [ramsey/uuid-doctrine](https://github.com/ramsey/uuid-doctrine)? 

Without this annotation, this class produce error `Can't instantiate custom generator : no custom generator definition`, when I try generate migration.

**Comment by nicklog** [comment]
It has to be "none". Now it should work I hope :P

**Comment by vsychov** [comment]
@nicklog, probably one problem more in services.yml, I think, that it should look something like this:
```
services:
    Shapecode\Bundle\Doctrine\SessionHandlerBundle\Command\ClearSessionCommand:
        autowire: true

    Shapecode\Bundle\Doctrine\SessionHandlerBundle\Session\Handler\DoctrineHandler:
        autowire: true

```

without enabled autowire it not gonna work

**Comment by nicklog** [comment]
Sorry, now it should work fine. I tested it local in a custom project.

**Comment by vsychov** [comment]
@nicklog , thanks for you grate job, now it works perfect. 
Can it be released as 3.x version?

**Comment by nicklog** [comment]
@vsychov Yeah, lets do this :)

**Pull request merged**
